name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the complete commit history is fetched

      - name: SSH into EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            cd games-with-friends && git reset --hard &&
            git pull origin master &&
            cd frontend && npm i && npm run build &&
            cd ../backend && npm i && npm run build && 
            pm2 restart backend &&
            sudo service nginx restart